In [74]:
import pandas
data=pandas.read_csv("boyGirlMarryNumber.csv",encoding="big5")
data["SUM"]=data.sum(axis=1)
data=data[data["SUM"]>5000]
data["IQR"]=data.quantile(0.75,axis=1)-data.quantile(0.25,axis=1)
print(data)

          index    93年    94年    95年    96年    97年    98年    99年   100年  \
1   男 / 15-19歲    1006    828    829    786    757    517    516    600
2   男 / 20-24歲   13096  12453  11753  10204   9680   6809   6954   7983
3   男 / 25-29歲   44918  51135  50737  45019  52484  35155  39710  47094
4   男 / 30-34歲   35948  40714  42795  42464  52096  38455  50141  61386
5   男 / 35-39歲   16866  17071  17955  18022  20342  16980  20265  24933
6   男 / 40-44歲    8237   7945   7855   7894   8367   7520   8752  10050
7   男 / 45-49歲    4618   4424   4229   4239   4546   4444   4874   5325
8   男 / 50-54歲    2684   2671   2714   2666   2762   2911   3035   3282
9   男 / 55-59歲    1254   1257   1345   1427   1603   1774   1879   2121
10  男 / 60-64歲     710    631    621    604    722    786    874    978
11   男 / 65歲以上    2109   2010   1833   1713   1505   1747   1819   1575
13  女 / 15-19歲    9287   5475   4124   3829   3527   2756   2424   2510
14  女 / 20-24歲   33935  33733  30186  26863  24502  18247  18273  19717
15  女 / 25-29歲   51344  61058  62566  57380  70055  46414  54730  66013
16  女 / 30-34歲   22232  25154  28617  29961  37235  30828  41457  50983
17  女 / 35-39歲    7380   7969   8746   8901  10459   9582  11580  14482
18  女 / 40-44歲    3521   3670   3952   3802   4218   3963   4478   5254
19  女 / 45-49歲    1893   2033   2196   2064   2277   2363   2687   2958
20  女 / 50-54歲    1002   1213   1286   1271   1437   1562   1627   1734
21  女 / 55-59歲     412    442    566    551    708    809    898    996

     101年   102年     SUM      IQR
1     672    704    7215    192.5
2    7938   8093   94963   4142.5
3   38041  37144  441437  12060.5
4   52441  54488  470928  11875.5
5   22663  24907  200004   6272.0
6    9267   9687   85574   1557.5
7    4950   5093   46742    587.5
8    3032   3091   28848    364.0
9    1879   1968   16507    537.5
10   1097   1172    8195    367.0
11   1404   1287   17002    381.5
13   2494   2597   39023   2246.0
14  18066  17502  241024  13699.5
15  52421  51751  573732  12203.5
16  45688  48468  360623  17789.0
17  13665  15738  108502   5250.0
18   4950   5442   43250   1225.0
19   2717   2709   23897    583.0
20   1665   1662   14459    385.0
21    945    991    7318    409.5